/** 常见中文化学名词 → PubChem 英文名映射。
 *  PubChem PUG REST 的名称索引基本只认英文，中文查询会 404；
 *  本词典作为 resolveCid 的回退层，覆盖高中化学常用物质。
 *  收录原则：只收录与 PubChem 英文名对应关系确定、无歧义的条目；
 *  混合物/矿石类若 PubChem 无单一分子记录则不收录。 */

export const ZH_TO_EN: Record<string, string> = {
  // —— 常见单质 ——
  '氢气': 'Hydrogen',
  '氧气': 'Oxygen',
  '氮气': 'Nitrogen',
  '氯气': 'Chlorine',
  '臭氧': 'Ozone',
  '溴': 'Bromine',
  '碘': 'Iodine',
  '硫': 'Sulfur',
  '硫磺': 'Sulfur',
  '白磷': 'White phosphorus',
  '红磷': 'Red phosphorus',
  '石墨': 'Graphite',
  '金刚石': 'Diamond',
  '铁': 'Iron',
  '铜': 'Copper',
  '铝': 'Aluminium',
  '锌': 'Zinc',
  '镁': 'Magnesium',
  '钠': 'Sodium',
  '钾': 'Potassium',
  '钙': 'Calcium',
  '银': 'Silver',
  '金': 'Gold',
  '水银': 'Mercury',
  '汞': 'Mercury',
  '铅': 'Lead',

  // —— 氧化物 ——
  '水': 'Water',
  '双氧水': 'Hydrogen peroxide',
  '过氧化氢': 'Hydrogen peroxide',
  '一氧化碳': 'Carbon monoxide',
  '二氧化碳': 'Carbon dioxide',
  '干冰': 'Carbon dioxide',
  '二氧化硅': 'Silicon dioxide',
  '二氧化硫': 'Sulfur dioxide',
  '三氧化硫': 'Sulfur trioxide',
  '二氧化氮': 'Nitrogen dioxide',
  '一氧化氮': 'Nitric oxide',
  '五氧化二磷': 'Phosphorus pentoxide',
  '氧化钠': 'Sodium oxide',
  '过氧化钠': 'Sodium peroxide',
  '氧化钾': 'Potassium oxide',
  '氧化钙': 'Calcium oxide',
  '生石灰': 'Calcium oxide',
  '氧化镁': 'Magnesium oxide',
  '氧化铝': 'Aluminium oxide',
  '氧化铁': 'Iron(III) oxide',
  '三氧化二铁': 'Iron(III) oxide',
  '四氧化三铁': 'Magnetite',
  '磁铁矿': 'Magnetite',
  '氧化铜': 'Copper(II) oxide',
  '二氧化锰': 'Manganese dioxide',

  // —— 酸 ——
  '盐酸': 'Hydrochloric acid',
  '硫酸': 'Sulfuric acid',
  '硝酸': 'Nitric acid',
  '碳酸': 'Carbonic acid',
  '磷酸': 'Phosphoric acid',
  '氢氟酸': 'Hydrofluoric acid',
  '醋酸': 'Acetic acid',
  '乙酸': 'Acetic acid',
  '甲酸': 'Formic acid',
  '蚁酸': 'Formic acid',
  '苯甲酸': 'Benzoic acid',
  '水杨酸': 'Salicylic acid',
  '乳酸': 'Lactic acid',
  '柠檬酸': 'Citric acid',

  // —— 碱 ——
  '氢氧化钠': 'Sodium hydroxide',
  '烧碱': 'Sodium hydroxide',
  '火碱': 'Sodium hydroxide',
  '苛性钠': 'Sodium hydroxide',
  '氢氧化钾': 'Potassium hydroxide',
  '氢氧化钙': 'Calcium hydroxide',
  '熟石灰': 'Calcium hydroxide',
  '消石灰': 'Calcium hydroxide',
  '氨水': 'Ammonium hydroxide',

  // —— 盐 ——
  '食盐': 'Sodium chloride',
  '氯化钠': 'Sodium chloride',
  '氯化钾': 'Potassium chloride',
  '氯化钙': 'Calcium chloride',
  '氯化镁': 'Magnesium chloride',
  '氯化铝': 'Aluminium chloride',
  '氯化铁': 'Iron(III) chloride',
  '氯化亚铁': 'Iron(II) chloride',
  '氯化铜': 'Copper(II) chloride',
  '氯化银': 'Silver chloride',
  '氯化铵': 'Ammonium chloride',
  '次氯酸钠': 'Sodium hypochlorite',
  '碳酸钙': 'Calcium carbonate',
  '石灰石': 'Calcium carbonate',
  '大理石': 'Calcium carbonate',
  '方解石': 'Calcium carbonate',
  '碳酸钠': 'Sodium carbonate',
  '纯碱': 'Sodium carbonate',
  '苏打': 'Sodium carbonate',
  '碳酸氢钠': 'Sodium bicarbonate',
  '小苏打': 'Sodium bicarbonate',
  '碳酸钾': 'Potassium carbonate',
  '硫酸铜': 'Copper(II) sulfate',
  '胆矾': 'Copper(II) sulfate',
  '蓝矾': 'Copper(II) sulfate',
  '硫酸亚铁': 'Iron(II) sulfate',
  '绿矾': 'Iron(II) sulfate',
  '硫酸钠': 'Sodium sulfate',
  '硫酸钡': 'Barium sulfate',
  '硫酸铵': 'Ammonium sulfate',
  '硝酸钾': 'Potassium nitrate',
  '硝酸钠': 'Sodium nitrate',
  '硝酸银': 'Silver nitrate',
  '硝酸铵': 'Ammonium nitrate',
  '高锰酸钾': 'Potassium permanganate',
  '明矾': 'Potassium alum',
  '碳酸氢铵': 'Ammonium bicarbonate',

  // —— 有机物 ——
  '甲烷': 'Methane',
  '乙烷': 'Ethane',
  '丙烷': 'Propane',
  '乙烯': 'Ethylene',
  '丙烯': 'Propylene',
  '乙炔': 'Acetylene',
  '苯': 'Benzene',
  '甲苯': 'Toluene',
  '苯酚': 'Phenol',
  '石炭酸': 'Phenol',
  '甲醇': 'Methanol',
  '乙醇': 'Ethanol',
  '酒精': 'Ethanol',
  '乙二醇': 'Ethylene glycol',
  '甘油': 'Glycerol',
  '丙三醇': 'Glycerol',
  '甲醛': 'Formaldehyde',
  '乙醛': 'Acetaldehyde',
  '丙酮': 'Acetone',
  '乙酸乙酯': 'Ethyl acetate',
  '尿素': 'Urea',
  '葡萄糖': 'Glucose',
  '果糖': 'Fructose',
  '蔗糖': 'Sucrose',
  '麦芽糖': 'Maltose',
  '阿司匹林': 'Aspirin',
  '咖啡因': 'Caffeine',
  '维生素 C': 'Ascorbic acid',
  '维生素C': 'Ascorbic acid',
  '抗坏血酸': 'Ascorbic acid',
};
